---
title: "codigo_transformar_dados"
format: html
editor: visual
---

```{r}
#| warning: true
#| include: false
library(readr) # read_csv
library(arrow) # parquet
library(JuliaCall) # usar julia dentro do R
library(ggplot2)
library(dplyr)

library(reticulate)
```

```{r}
# Convertendo o YellowCab 2023 Jan de Parquet para CSV
arquivo_parquet_entrada_yellowcab <- "long- yellow_tripdata2023-01/yellow_tripdata_2023-01.parquet"
arquivo_csv_saida_yellowcab <- "long- yellow_tripdata2023-01/yellow_tripdata_2023-01.csv"


dados <- read_parquet(arquivo_parquet_entrada)

write_csv_arrow(dados, arquivo_csv_saida)

print("Arquivo convertido!")
```

```{r}
arquivo_csv_stackoverflow <- "ancho-stack-overflow-developer-survey-2024/survey_results_public.csv"

arquivo_csv_saida_stackoverflow <- "ancho-stack-overflow-developer-survey-2024/survey_results_public.parquet"

dados_stackoverflow <- read_csv(arquivo_csv_stackoverflow)

write_parquet(dados_stackoverflow, arquivo_csv_saida_stackoverflow)

print("Arquivo convertido!")
```

```{r}
# 38 milhões de linhas
# 19 colunas
arquivo_csv_yellowcabfull <- "giga-yellow_taxidata2023/2023_Yellow_Taxi_Trip_Data_20251021.csv"

arquivo_csv_saida_yellowcabfull <- "giga-yellow_taxidata2023/2023_Yellow_Taxi_Trip_Data_20251021.parquet"

dados_fullcab <- read_csv(arquivo_csv_yellowcabfull)

write_parquet(dados_fullcab, arquivo_csv_saida_yellowcabfull)
```
